spring:
  datasource:
    url: jdbc:mysql://112.124.12.211:3306/lyf_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  cloud:
    nacos:
      discovery:
        server-addr: 112.124.12.211:8848
  application:
    name: lyf-ums
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/**/*.xml


server:
  port: 15000