spring:
  datasource:
    url: jdbc:mysql://112.124.12.211:3306/lyf_food?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 112.124.12.211:8848
  application:
      name: lyf-food

  redis:
    host: 112.124.12.211
    port: 6379
mybatis-plus:

  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/**/*.xml



server:
  port: 8000

feign:
  client:
    default-config:
      connect-timeout: 10000
      read-timeout: 10000


